;;冰月http://mir.jycrc.com/bbs/
[Nomal]
MessName="〖冰月孤魂玩家短信息系统〗"
Maxperson=10
;默认每个玩家允许保留在服务器的最多短信息,请不要超过30条,否则后果自负.
PostMoney=5000
;发送短信息花费金币数
MaxQFnum=10
;默认群发数量，最多允许20
[totalcount]
Num=6
;当前短信息记数，默认=0
[Act]
lock=0
;锁定标志，默认=0

